name: Latest Blog Posts

on:
  schedule:
    # Runs every day at 1am
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/royalesnaaier,https://medium.com/feed/@royalesnaaier"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"
          commit_message: "Updated with the latest blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
